In [11]:
from datetime import datetime

import pandas as pd


def read_data(ticker = "BTC", timeframe="1W") -> pd.DataFrame:
    _data = pd.read_csv(f"../../data/INDEX_{ticker}USD_{timeframe}.csv")
    _data.rename(
        columns={
            "MA": "MA100",
            #"ATR": "ATR1",
            #"ATR.1": "ATR14",
            "MA.1": "MA8",
            "MA.2": "MA50",
            "20w SMA": "MA20",
            "21w EMA": "EMA21",
            #"RSI-based MA": "RSI MA",
            "time": "DateTime",
        }, 
        inplace=True
    )
    _data = _data[
        [
            "DateTime",
            "open",
            "high",
            "low",
            "close",
            "Volume",
            #"Volume MA",
            "MA100",
            "MA50",
            "EMA21",
            "MA20",
            "MA8",
            #"RSI",
            #"RSI MA",
            #"ATR1",
            #"ATR14",
        ]
    ]
    _data["DateTime"] = _data["DateTime"].apply(
        lambda row: datetime.fromtimestamp(row)
    )

    return _data

In [77]:
trading_view_data = read_data("BTC", "1W")
trading_view_data

,DateTime,open,high,low,close,Volume,MA100,MA50,EMA21,MA20,MA8
0,2011-12-19,3.19300,4.50000,3.18933,4.22500,548627.494657,2.761738,5.448742,4.749152,4.950492,3.016694
1,2011-12-26,4.22500,5.49990,3.81000,5.26766,485200.264821,2.814408,5.547636,4.796289,4.674090,3.305203
2,2012-01-02,5.26346,7.22000,4.65000,7.11358,831478.824369,2.885537,5.682171,5.006952,4.464207,3.819793
3,2012-01-09,7.08362,7.19100,5.81000,7.00177,762534.117275,2.955549,5.813359,5.188299,4.360789,4.420014
4,2012-01-16,7.00177,7.18888,4.64000,6.30970,854016.604782,3.018639,5.929955,5.290245,4.267375,4.898738
...,...,...,...,...,...,...,...,...,...,...,...
633,2024-02-05,42578.80000,48576.25000,42244.23000,48311.33000,124007.204529,28177.380400,31911.179800,38840.135645,38260.803500,43184.257500
634,2024-02-12,48317.79000,52829.25000,47694.17000,52127.48000,154129.198244,28285.881100,32505.149800,40048.076041,39467.408000,44321.570000
635,2024-02-19,52135.18000,52971.70000,50428.75000,51725.45000,103586.979290,28334.568900,33094.792000,41109.655492,40657.052500,45502.465000
636,2024-02-26,51731.94000,64005.20000,50907.81000,63148.92000,257332.623029,28501.898200,33796.731600,43113.224993,42455.770500,47903.292500
637,2024-03-04,63146.76000,70055.50000,59173.92000,69342.56000,304078.816055,28773.765000,34623.562800,45497.709993,44422.693000,51356.661250

In [21]:
close = data.close.values
ma100 = data.MA100.values
print(len(close))
print(len(ma100))
ma100

638
638

array([2.76173848e+00, 2.81440776e+00, 2.88553738e+00, 2.95554881e+00,
       3.01863947e+00, 3.07244129e+00, 3.12932221e+00, 3.18444101e+00,
       3.22827539e+00, 3.27746240e+00, 3.32562515e+00, 3.37468462e+00,
       3.42743230e+00, 3.47287942e+00, 3.52109470e+00, 3.56898990e+00,
       3.61864910e+00, 3.67064930e+00, 3.71965340e+00, 3.77010750e+00,
       3.81936210e+00, 3.87021230e+00, 3.92155190e+00, 3.97355890e+00,
       4.02817380e+00, 4.08974200e+00, 4.15238380e+00, 4.21816860e+00,
       4.28554740e+00, 4.36114850e+00, 4.44459160e+00, 4.53103430e+00,
       4.63909410e+00, 4.75471800e+00, 4.83410300e+00, 4.93957600e+00,
       5.04099700e+00, 5.15058590e+00, 5.26832090e+00, 5.38923400e+00,
       5.51208390e+00, 5.62815900e+00, 5.74214800e+00, 5.85566830e+00,
       5.95990060e+00, 6.06520170e+00, 6.17198870e+00, 6.28630390e+00,
       6.40872390e+00, 6.53107430e+00, 6.66097460e+00, 6.79074480e+00,
       6.91999710e+00, 7.05007320e+00, 7.17981370e+00, 7.31199880e+00,
       7.45849880e+00, 7.62818090e+00, 7.82518090e+00, 8.05587940e+00,
       8.31510050e+00, 8.60658960e+00, 8.94336950e+00, 9.39557950e+00,
       9.86221050e+00, 1.05660875e+01, 1.14800766e+01, 1.30727557e+01,
       1.39340966e+01, 1.50562265e+01, 1.63337699e+01, 1.74092709e+01,
       1.83904711e+01, 1.94300071e+01, 2.05899071e+01, 2.16605022e+01,
       2.25158765e+01, 2.33832765e+01, 2.43254764e+01, 2.51670764e+01,
       2.58530764e+01, 2.66893180e+01, 2.74961855e+01, 2.83932846e+01,
       2.93627048e+01, 3.03540613e+01, 3.14358613e+01, 3.26036715e+01,
       3.40135017e+01, 3.52356230e+01, 3.65830549e+01, 3.78913550e+01,
       3.92974952e+01, 4.06458993e+01, 4.20912307e+01, 4.39304307e+01,
       4.59756326e+01, 4.81874518e+01, 5.15182509e+01, 5.67695200e+01,
       6.46772700e+01, 7.46688326e+01, 8.26376969e+01, 9.17676792e+01,
       9.79945822e+01, 1.05223773e+02, 1.14266885e+02, 1.22484138e+02,
       1.30799271e+02, 1.38875051e+02, 1.46966851e+02, 1.53857751e+02,
       1.60054957e+02, 1.66079457e+02, 1.71684906e+02, 1.78021981e+02,
       1.84302292e+02, 1.89830256e+02, 1.94391211e+02, 1.98928512e+02,
       2.03059213e+02, 2.08017813e+02, 2.12266324e+02, 2.16564686e+02,
       2.20889703e+02, 2.25302065e+02, 2.30978465e+02, 2.37176375e+02,
       2.43695385e+02, 2.49558075e+02, 2.55507979e+02, 2.61440376e+02,
       2.67705476e+02, 2.73884136e+02, 2.80044136e+02, 2.85853536e+02,
       2.91608595e+02, 2.97384495e+02, 3.02239795e+02, 3.07226062e+02,
       3.11880162e+02, 3.16560962e+02, 3.21208573e+02, 3.25084362e+02,
       3.28744363e+02, 3.31835362e+02, 3.35507175e+02, 3.39270859e+02,
       3.42676138e+02, 3.45789338e+02, 3.49282538e+02, 3.53066038e+02,
       3.56615418e+02, 3.60279817e+02, 3.63905478e+02, 3.67300818e+02,
       3.70351718e+02, 3.73342936e+02, 3.75778936e+02, 3.78211938e+02,
       3.80054092e+02, 3.82302492e+02, 3.84226693e+02, 3.86005193e+02,
       3.87889993e+02, 3.89539992e+02, 3.91233692e+02, 3.92366582e+02,
       3.94335582e+02, 3.95831782e+02, 3.96914738e+02, 3.98359938e+02,
       3.99575538e+02, 4.00572138e+02, 4.01434138e+02, 4.02614838e+02,
       4.04017763e+02, 4.05380263e+02, 4.06707863e+02, 4.08019763e+02,
       4.09487363e+02, 4.10878565e+02, 4.12401085e+02, 4.13900385e+02,
       4.15568785e+02, 4.17630185e+02, 4.19246785e+02, 4.20955774e+02,
       4.22320074e+02, 4.23712724e+02, 4.24928722e+02, 4.25874022e+02,
       4.26735082e+02, 4.27766782e+02, 4.28601082e+02, 4.29061082e+02,
       4.29324781e+02, 4.29479681e+02, 4.28596271e+02, 4.25963171e+02,
       4.20861071e+02, 4.14119132e+02, 4.09820132e+02, 4.03825332e+02,
       4.00781932e+02, 3.97237832e+02, 3.92043832e+02, 3.88105032e+02,
       3.84172232e+02, 3.80270432e+02, 3.76414332e+02, 3.73967832e+02,
       3.71538032e+02, 3.69495732e+02, 3.67497213e+02, 3.64832313e+02,
       3.62585313e+02, 3.61410213e+02, 3.61144714e+02, 3.60594414e+02,
       3.60533114e+02, 3.59636113e+02, 3.59609813e+02, 3.59465400e+02,
       3.59298900e+02, 3.59110000e+02, 3.58000300e+02, 3.56247200e+02,
       3.54258900e+02, 3.52898900e+02, 3.51239700e+02, 3.50530200e+02,
       3.49896600e+02, 3.50321700e+02, 3.51754700e+02, 3.52233375e+02,
       3.52967125e+02, 3.53584175e+02, 3.55414700e+02, 3.56931015e+02,
       3.58395115e+02, 3.59538840e+02, 3.60488865e+02, 3.62297315e+02,
       3.64274422e+02, 3.67158048e+02, 3.69448238e+02, 3.71668985e+02,
       3.74140480e+02, 3.77010372e+02, 3.79541722e+02, 3.82034597e+02,
       3.84872030e+02, 3.88057622e+02, 3.91431415e+02, 3.94915040e+02,
       3.98997432e+02, 4.03115132e+02, 4.08134932e+02, 4.13168335e+02,
       4.18967587e+02, 4.25371710e+02, 4.33065987e+02, 4.39987485e+02,
       4.45903782e+02, 4.52801207e+02, 4.59326887e+02, 4.66713952e+02,
       4.73893745e+02, 4.81760570e+02, 4.91115645e+02, 5.01245505e+02,
       5.11179677e+02, 5.19123145e+02, 5.26581383e+02, 5.35192955e+02,
       5.44881280e+02, 5.54268050e+02, 5.64319150e+02, 5.75652417e+02,
       5.89097103e+02, 6.04676803e+02, 6.22513442e+02, 6.41975275e+02,
       6.64486252e+02, 6.90970050e+02, 7.13344305e+02, 7.35396403e+02,
       7.57658105e+02, 7.80030532e+02, 7.96533155e+02, 8.21812730e+02,
       8.47051205e+02, 8.76888335e+02, 9.15190435e+02, 9.53463970e+02,
       9.94523095e+02, 1.03834004e+03, 1.07838054e+03, 1.11277650e+03,
       1.14661340e+03, 1.18717227e+03, 1.22942120e+03, 1.28308602e+03,
       1.33970597e+03, 1.39731742e+03, 1.46725932e+03, 1.52164095e+03,
       1.59745320e+03, 1.68611169e+03, 1.79434357e+03, 1.94022504e+03,
       2.12768757e+03, 2.26425942e+03, 2.39948745e+03, 2.55720932e+03,
       2.68973054e+03, 2.80074224e+03, 2.91260922e+03, 2.99020185e+03,
       3.06675812e+03, 3.16673089e+03, 3.25836487e+03, 3.36894002e+03,
       3.46004197e+03, 3.53765870e+03, 3.61754925e+03, 3.68116452e+03,
       3.74677705e+03, 3.82577365e+03, 3.90939077e+03, 3.99804950e+03,
       4.08838010e+03, 4.16857605e+03, 4.24607657e+03, 4.31310502e+03,
       4.38360625e+03, 4.44482655e+03, 4.50248632e+03, 4.55737051e+03,
       4.61460536e+03, 4.67569821e+03, 4.73343673e+03, 4.80162586e+03,
       4.87803835e+03, 4.94225967e+03, 4.99933208e+03, 5.05807644e+03,
       5.11914172e+03, 5.18594507e+03, 5.24268167e+03, 5.30115117e+03,
       5.36101844e+03, 5.41969040e+03, 5.47828466e+03, 5.53308911e+03,
       5.58992856e+03, 5.64669669e+03, 5.70326006e+03, 5.75913976e+03,
       5.80683166e+03, 5.83723536e+03, 5.86829286e+03, 5.89445809e+03,
       5.91811169e+03, 5.94829311e+03, 5.97745381e+03, 6.00772037e+03,
       6.03281375e+03, 6.05760123e+03, 6.08113695e+03, 6.10255407e+03,
       6.12673989e+03, 6.15283103e+03, 6.18049974e+03, 6.20736187e+03,
       6.23425580e+03, 6.26216493e+03, 6.28940508e+03, 6.31673801e+03,
       6.35300037e+03, 6.38670252e+03, 6.41938976e+03, 6.44901358e+03,
       6.48092645e+03, 6.52109190e+03, 6.57793560e+03, 6.64033162e+03,
       6.70264375e+03, 6.75399834e+03, 6.82468467e+03, 6.90542452e+03,
       6.98543530e+03, 7.06793884e+03, 7.13032414e+03, 7.19567001e+03,
       7.24758046e+03, 7.31114818e+03, 7.38393643e+03, 7.45008748e+03,
       7.51476658e+03, 7.56858558e+03, 7.62663238e+03, 7.67285281e+03,
       7.71325573e+03, 7.73242861e+03, 7.73717301e+03, 7.76126258e+03,
       7.76337178e+03, 7.76598058e+03, 7.74552186e+03, 7.68548673e+03,
       7.57921031e+03, 7.50769523e+03, 7.44285078e+03, 7.35664208e+03,
       7.29118766e+03, 7.25088576e+03, 7.20855391e+03, 7.20045071e+03,
       7.20155576e+03, 7.18447196e+03, 7.17446918e+03, 7.15292826e+03,
       7.15929018e+03, 7.17661733e+03, 7.19178048e+03, 7.20892826e+03,
       7.21908178e+03, 7.18893763e+03, 7.15918656e+03, 7.12398236e+03,
       7.09568171e+03, 7.07783116e+03, 7.06396041e+03, 7.06756911e+03,
       7.07956088e+03, 7.09909803e+03, 7.13134081e+03, 7.15699301e+03,
       7.18800546e+03, 7.21849601e+03, 7.24833943e+03, 7.26720943e+03,
       7.27621518e+03, 7.29670013e+03, 7.32658088e+03, 7.35387548e+03,
       7.38623706e+03, 7.42398701e+03, 7.47797113e+03, 7.53227263e+03,
       7.58239531e+03, 7.63386966e+03, 7.67072231e+03, 7.71224898e+03,
       7.75733033e+03, 7.80105486e+03, 7.84356158e+03, 7.89372851e+03,
       7.95325838e+03, 8.04432441e+03, 8.14098536e+03, 8.26050188e+03,
       8.38827066e+03, 8.53325673e+03, 8.67691953e+03, 8.83033268e+03,
       8.98683853e+03, 9.18628598e+03, 9.41355901e+03, 9.71037021e+03,
       1.00556199e+04, 1.03775900e+04, 1.06631762e+04, 1.09566839e+04,
       1.13063800e+04, 1.17533271e+04, 1.22885467e+04, 1.26999799e+04,
       1.31578131e+04, 1.36961695e+04, 1.42169894e+04, 1.47232822e+04,
       1.52482483e+04, 1.57782404e+04, 1.62589908e+04, 1.66628448e+04,
       1.71417042e+04, 1.76483554e+04, 1.80231322e+04, 1.82621353e+04,
       1.85113533e+04, 1.87546349e+04, 1.90419031e+04, 1.92918855e+04,
       1.95434920e+04, 1.97866454e+04, 2.00138564e+04, 2.02285008e+04,
       2.04814195e+04, 2.07824161e+04, 2.11168055e+04, 2.14839379e+04,
       2.18765574e+04, 2.22840349e+04, 2.27233590e+04, 2.31009431e+04,
       2.34910889e+04, 2.38275465e+04, 2.42178454e+04, 2.46744749e+04,
       2.52047902e+04, 2.57444587e+04, 2.62839963e+04, 2.68418907e+04,
       2.74257656e+04, 2.79385941e+04, 2.84379421e+04, 2.88585110e+04,
       2.92778512e+04, 2.96580909e+04, 3.00802031e+04, 3.04601991e+04,
       3.07771785e+04, 3.11090376e+04, 3.13722743e+04, 3.16662992e+04,
       3.20101107e+04, 3.23774170e+04, 3.27030416e+04, 3.30213900e+04,
       3.33378499e+04, 3.36466927e+04, 3.39881640e+04, 3.43796994e+04,
       3.47547754e+04, 3.50890736e+04, 3.53892430e+04, 3.56967390e+04,
       3.59870425e+04, 3.62297922e+04, 3.64494281e+04, 3.66592096e+04,
       3.68625426e+04, 3.70707477e+04, 3.72433751e+04, 3.73567650e+04,
       3.74676318e+04, 3.75498971e+04, 3.76414501e+04, 3.77302027e+04,
       3.78395550e+04, 3.79555837e+04, 3.80848190e+04, 3.82246079e+04,
       3.83303565e+04, 3.84180779e+04, 3.85113869e+04, 3.86160255e+04,
       3.86951035e+04, 3.87527676e+04, 3.88056590e+04, 3.88452766e+04,
       3.88782135e+04, 3.88895073e+04, 3.89138204e+04, 3.89291451e+04,
       3.89005875e+04, 3.88283491e+04, 3.87299973e+04, 3.85701716e+04,
       3.83593374e+04, 3.81685691e+04, 3.80139481e+04, 3.78486958e+04,
       3.76312587e+04, 3.73534960e+04, 3.70057526e+04, 3.67908759e+04,
       3.65104864e+04, 3.61383857e+04, 3.58074845e+04, 3.54852088e+04,
       3.51273891e+04, 3.47500697e+04, 3.44678704e+04, 3.42566482e+04,
       3.39722889e+04, 3.36726247e+04, 3.35113158e+04, 3.34399725e+04,
       3.33756901e+04, 3.33036009e+04, 3.31826432e+04, 3.30942533e+04,
       3.30281637e+04, 3.29464704e+04, 3.28633509e+04, 3.28089323e+04,
       3.27593811e+04, 3.26669573e+04, 3.25302774e+04, 3.23625595e+04,
       3.21705980e+04, 3.19754800e+04, 3.17480984e+04, 3.15806071e+04,
       3.13700752e+04, 3.11991010e+04, 3.09764681e+04, 3.06878932e+04,
       3.03379535e+04, 2.99918244e+04, 2.96582020e+04, 2.93043999e+04,
       2.89211208e+04, 2.86332187e+04, 2.84053760e+04, 2.82617912e+04,
       2.81313508e+04, 2.80380098e+04, 2.79045820e+04, 2.78310681e+04,
       2.78503533e+04, 2.78328899e+04, 2.79002591e+04, 2.79437430e+04,
       2.79589897e+04, 2.79554082e+04, 2.79874121e+04, 2.80306229e+04,
       2.80721753e+04, 2.81773804e+04, 2.82858811e+04, 2.83345689e+04,
       2.85018982e+04, 2.87737650e+04])

In [25]:
import numpy as np


def calculate_moving_average(close_price, ma_length):
    weights = np.ones(ma_length) / ma_length
    print(weights)
    moving_average = np.convolve(close_price, weights, mode="valid")
    moving_average_with_nans = np.concatenate((np.full(ma_length - 1, np.nan), moving_average))
    return moving_average_with_nans

In [27]:
_ma100 = calculate_moving_average(close, 100)
print(len(_ma100))
_ma100

[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]
638

array([          nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,    56.76952  ,
          64.67727  ,    74.6688326,    82.6376969,    91.7676792,
          97.9945822,   105.2237732,   114.2668851,   122.4841383,
         130.7992714,   138.8750514,   146.9668513,   153.8577513,
         160.054957 ,   166.0794569,   171.684906 ,   178.0219808,
         184.3022916,   189.8302564,   194.3912113,   198.9285122,
         203.0592126,   208.0178134,   212.2663238,   216.5646858,
         220.8897029,   225.3020647,   230.9784645,   237.1763747,
         243.6953849,   249.5580748,   255.5079788,   261.4403761,
         267.7054763,   273.8841364,   280.0441364,   285.8535364,
         291.6085954,   297.3844954,   302.2397954,   307.2260623,
         311.8801623,   316.5609622,   321.2085732,   325.0843625,
         328.7443627,   331.8353616,   335.5071746,   339.2708594,
         342.6761384,   345.789338 ,   349.282538 ,   353.0660378,
         356.6154176,   360.2798175,   363.905478 ,   367.3008179,
         370.3517179,   373.3429358,   375.7789358,   378.2119383,
         380.0540923,   382.3024924,   384.2266925,   386.0051925,
         387.8899925,   389.5399925,   391.2336924,   392.3665822,
         394.3355823,   395.8317823,   396.9147379,   398.3599379,
         399.5755377,   400.5721377,   401.4341377,   402.6148377,
         404.0177634,   405.3802634,   406.7078634,   408.0197634,
         409.4873634,   410.8785648,   412.4010848,   413.9003846,
         415.5687846,   417.6301846,   419.2467846,   420.9557744,
         422.3200741,   423.712724 ,   424.928722 ,   425.8740219,
         426.7350817,   427.7667817,   428.6010817,   429.0610817,
         429.3247807,   429.4796806,   428.5962705,   425.9631714,
         420.8610714,   414.1191322,   409.8201321,   403.8253321,
         400.7819321,   397.2378321,   392.0438321,   388.1050321,
         384.1722321,   380.2704321,   376.4143321,   373.9678321,
         371.5380321,   369.4957321,   367.497213 ,   364.832313 ,
         362.585313 ,   361.410213 ,   361.144714 ,   360.594414 ,
         360.533114 ,   359.636113 ,   359.609813 ,   359.4654   ,
         359.2989   ,   359.11     ,   358.0003   ,   356.2472   ,
         354.2589   ,   352.8989   ,   351.2397   ,   350.5302   ,
         349.8966   ,   350.3217   ,   351.7547   ,   352.233375 ,
         352.967125 ,   353.584175 ,   355.4147   ,   356.931015 ,
         358.395115 ,   359.53884  ,   360.488865 ,   362.297315 ,
         364.2744225,   367.1580475,   369.4482375,   371.668985 ,
         374.14048  ,   377.0103725,   379.5417225,   382.0345975,
         384.87203  ,   388.0576225,   391.431415 ,   394.91504  ,
         398.9974325,   403.1151325,   408.1349325,   413.168335 ,
         418.9675875,   425.37171  ,   433.0659875,   439.987485 ,
         445.9037825,   452.8012075,   459.3268875,   466.7139525,
         473.893745 ,   481.76057  ,   491.115645 ,   501.245505 ,
         511.1796775,   519.123145 ,   526.5813825,   535.192955 ,
         544.88128  ,   554.26805  ,   564.31915  ,   575.6524175,
         589.0971025,   604.6768025,   622.5134425,   641.975275 ,
         664.4862525,   690.97005  ,   713.344305 ,   735.3964025,
         757.658105 ,   780.0305325,   796.533155 ,   821.81273  ,
         847.051205 ,   876.888335 ,   915.190435 ,   953.46397  ,
         994.523095 ,  1038.340045 ,  1078.380545 ,  1112.776495 ,
        1146.613395 ,  1187.17227  ,  1229.421195 ,  1283.08602  ,
        1339.70597  ,  1397.31742  ,  1467.25932  ,  1521.640945 ,
        1597.453195 ,  1686.111695 ,  1794.34357  ,  1940.225045 ,
        2127.68757  ,  2264.25942  ,  2399.487445 ,  2557.20932  ,
        2689.730545 ,  2800.742245 ,  2912.60922  ,  2990.201845 ,
        3066.75812  ,  3166.730895 ,  3258.36487  ,  3368.94002  ,
        3460.04197  ,  3537.658695 ,  3617.549245 ,  3681.16452  ,
        3746.777045 ,  3825.773645 ,  3909.39077  ,  3998.049495 ,
        4088.380095 ,  4168.576045 ,  4246.07657  ,  4313.10502  ,
        4383.606245 ,  4444.826545 ,  4502.48632  ,  4557.370505 ,
        4614.605355 ,  4675.698205 ,  4733.43673  ,  4801.625855 ,
        4878.0383475,  4942.2596725,  4999.3320825,  5058.076435 ,
        5119.141715 ,  5185.9450725,  5242.6816725,  5301.1511725,
        5361.01844  ,  5419.6903975,  5478.284655 ,  5533.089105 ,
        5589.9285625,  5646.6966875,  5703.2600625,  5759.13976  ,
        5806.8316575,  5837.23536  ,  5868.2928575,  5894.458085 ,
        5918.1116875,  5948.2931125,  5977.4538075,  6007.7203675,
        6032.81375  ,  6057.601225 ,  6081.13695  ,  6102.554065 ,
        6126.7398925,  6152.831025 ,  6180.4997375,  6207.361865 ,
        6234.2557962,  6262.1649262,  6289.4050762,  6316.7380087,
        6353.0003737,  6386.7025237,  6419.3897587,  6449.0135762,
        6480.9264487,  6521.0919012,  6577.9355962,  6640.3316237,
        6702.6437462,  6753.9983437,  6824.6846712,  6905.4245212,
        6985.4352962,  7067.9388412,  7130.3241412,  7195.6700062,
        7247.5804562,  7311.1481812,  7383.9364312,  7450.0874812,
        7514.7665812,  7568.5855812,  7626.6323812,  7672.8528062,
        7713.2557312,  7732.4286062,  7737.1730062,  7761.2625812,
        7763.3717812,  7765.9805812,  7745.5218562,  7685.4867312,
        7579.2103062,  7507.6952312,  7442.8507812,  7356.6420812,
        7291.1876562,  7250.8857562,  7208.5539062,  7200.4507062,
        7201.5557562,  7184.4719562,  7174.4691812,  7152.9282562,
        7159.2901812,  7176.6173312,  7191.7804812,  7208.9282562,
        7219.0817812,  7188.9376312,  7159.1865562,  7123.9823562,
        7095.6817062,  7077.8311562,  7063.9604062,  7067.5691062,
        7079.5608812,  7099.0980312,  7131.3408062,  7156.9930062,
        7188.0054562,  7218.4960062,  7248.3394312,  7267.2094312,
        7276.2151812,  7296.7001312,  7326.5808812,  7353.8754812,
        7386.2370562,  7423.9870062,  7477.9711312,  7532.2726312,
        7582.3953062,  7633.8696562,  7670.7223062,  7712.2489812,
        7757.3303312,  7801.0548562,  7843.5615812,  7893.7285062,
        7953.2583812,  8044.3244062,  8140.9853562,  8260.5018812,
        8388.2706562,  8533.2567312,  8676.9195312,  8830.3326812,
        8986.8385312,  9186.2859812,  9413.5590062,  9710.3702062,
       10055.6198562, 10377.5900062, 10663.1761562, 10956.6839062,
       11306.38005  , 11753.32715  , 12288.5467   , 12699.9799   ,
       13157.8131   , 13696.16955  , 14216.98945  , 14723.282225 ,
       15248.2483   , 15778.24045  , 16258.9908   , 16662.844775 ,
       17141.704225 , 17648.355425 , 18023.1322   , 18262.13535  ,
       18511.3533   , 18754.634875 , 19041.903125 , 19291.885475 ,
       19543.491975 , 19786.64545  , 20013.856375 , 20228.500775 ,
       20481.41955  , 20782.4161   , 21116.805525 , 21483.9379   ,
       21876.5574   , 22284.0349   , 22723.358975 , 23100.9431   ,
       23491.088925 , 23827.546525 , 24217.845425 , 24674.474875 ,
       25204.79025  , 25744.45875  , 26283.996275 , 26841.890675 ,
       27425.765575 , 27938.594075 , 28437.94215  , 28858.511025 ,
       29277.8512   , 29658.090925 , 30080.203125 , 30460.1991   ,
       30777.178525 , 31109.03765  , 31372.27435  , 31666.2992   ,
       32010.11075  , 32377.417    , 32703.04165  , 33021.390025 ,
       33337.849875 , 33646.692675 , 33988.164    , 34379.699375 ,
       34754.775425 , 35089.073625 , 35389.24305  , 35696.73905  ,
       35987.04255  , 36229.792225 , 36449.42815  , 36659.209575 ,
       36862.542625 , 37070.747725 , 37243.375075 , 37356.764975 ,
       37467.631825 , 37549.897125 , 37641.45015  , 37730.202675 ,
       37839.555    , 37955.5837   , 38084.819    , 38224.60795  ,
       38330.35655  , 38418.0779   , 38511.3869   , 38616.025475 ,
       38695.10355  , 38752.7676   , 38805.658975 , 38845.276625 ,
       38878.21345  , 38889.507325 , 38913.82035  , 38929.145075 ,
       38900.58755  , 38828.3491   , 38729.997275 , 38570.1716   ,
       38359.33735  , 38168.5691   , 38013.9481   , 37848.69575  ,
       37631.25865  , 37353.49595  , 37005.75255  , 36790.87585  ,
       36510.4864   , 36138.3857   , 35807.484525 , 35485.2088   ,
       35127.389075 , 34750.069675 , 34467.870375 , 34256.648175 ,
       33972.2889   , 33672.624675 , 33511.31575  , 33439.972475 ,
       33375.690075 , 33303.600925 , 33182.643175 , 33094.253325 ,
       33028.16365  , 32946.4704   , 32863.350925 , 32808.932325 ,
       32759.38105  , 32666.957325 , 32530.277375 , 32362.55945  ,
       32170.597975 , 31975.47995  , 31748.098375 , 31580.60705  ,
       31370.075175 , 31199.100975 , 30976.468125 , 30687.893225 ,
       30337.95345  , 29991.824375 , 29658.201975 , 29304.3999   ,
       28921.1208   , 28633.2187   , 28405.376    , 28261.7912   ,
       28131.3508   , 28038.0098   , 27904.582    , 27831.0681   ,
       27850.3533   , 27832.8899   , 27900.2591   , 27943.743    ,
       27958.9897   , 27955.4082   , 27987.4121   , 28030.6229   ,
       28072.1753   , 28177.3804   , 28285.8811   , 28334.5689   ,
       28501.8982   , 28773.765    ])

In [32]:
import requests

import numpy as np
import pandas as pd

API_KEY = "2MFXTQbLznmW0oV330ZTA5bhXU5"
GLASSNODE_OHLC_URL = r"https://api.glassnode.com/v1/metrics/market/price_usd_ohlc"

def get_glassnode_data(ticker: str = "BTC") -> pd.DataFrame:
    """
    """
    res = requests.get(
        GLASSNODE_OHLC_URL,
        params={"a": ticker, "api_key": API_KEY}
    )
    print(res)
    ohlc = pd.read_json(res.text, convert_dates=["t"]).set_index(["t"])

    df = pd.DataFrame(
        np.array([[v for v in date.values()] for date in ohlc.o])
    )
    df.rename(columns={0: "Open", 1: "High", 2: "Low", 3: "Close"}, inplace=True)
    
    df["Date"] = ohlc.index
    df.set_index(["Date"], inplace=True)

    return df

In [34]:
import yfinance as yf

In [40]:
from datetime import datetime, timedelta
from typing import Tuple

def _start_and_end_date(interval: str) -> Tuple[datetime, datetime]:
    ALLOWABLE_TIMES = {
        "long_term": ["1d", "1wk", "1mo"],
        "mid_term": ["1h"],
        "short_term": ["5m", "15m", "30m"],
        "shorter_term": ["1m"],
    }
    end = datetime.now()
    if interval in ALLOWABLE_TIMES["long_term"]:
        start = None
    elif interval in ALLOWABLE_TIMES["mid_term"]:
        start = end - timedelta(730)
    elif interval in ALLOWABLE_TIMES["short_term"]:
        start = end - timedelta(60)
    elif interval in ALLOWABLE_TIMES["shorter_term"]:
        start = end - timedelta(7)
    else:
        raise ValueError(f"Time step provided ({interval}) not valid {list(ALLOWABLE_TIMES.values())}")
            
    return start, end

def get_yahoo_data(ticker: str = "BTC-USD", interval: str = "1wk") -> pd.DataFrame:
    start, end = _start_and_end_date(interval)

    data = yf.download(
        tickers = ticker,
        interval = interval,
        start = start,
        end = end,
    )

    return data

In [41]:
data = get_yahoo_data()
data

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-09-15,465.864014,468.174011,384.532013,398.821014,398.821014,156903400
2014-09-22,399.100006,441.557007,374.332001,377.181000,377.181000,186772600
2014-09-29,376.928009,391.378998,289.295990,320.510010,320.510010,276657896
2014-10-06,320.389008,382.726013,302.559998,378.549011,378.549011,341152804
2014-10-13,377.920990,411.697998,368.897003,389.545990,389.545990,156902070
...,...,...,...,...,...,...
2024-02-12,48296.386719,52820.066406,47745.761719,52122.546875,52122.546875,213560041471
2024-02-19,52134.812500,52945.050781,50561.777344,51733.238281,51733.238281,160769145627
2024-02-26,51730.539062,63913.132812,50931.031250,63167.371094,63167.371094,322895666089
2024-03-04,63137.003906,70083.054688,59323.910156,69019.789062,69019.789062,405709693297
2024-03-11,69020.546875,73650.562500,67194.882812,70629.617188,70629.617188,225898382518

In [74]:
res = requests.get(
    "https://api.kraken.com/0/public/OHLC",
    params={"pair": "BTCUSD", "interval": 10080}
)
df = pd.DataFrame(res.json()["result"]["XXBTZUSD"])
df.rename(
    columns={0: "datetime", 1: "open", 2: "high", 3: "low", 4: "close", 5: "vwap", 6: "volume", 7: "count"}, 
    inplace=True,
)
df["datetime"] = pd.to_datetime(df["datetime"], unit="s")

for feature in df.columns:
    if feature == "count":
        df[feature] = df[feature].astype(int)
    elif feature in ["open", "high", "low", "close", "vwap"]:
        df[feature] = df[feature].astype(float)
df

,datetime,open,high,low,close,vwap,volume,count
0,2013-10-03,123.9,123.9,123.9,123.9,123.9,1.99160000,2
1,2013-10-10,134.5,153.0,133.8,141.2,136.9,3.45575337,8
2,2013-10-17,166.5,202.9,150.0,202.9,177.0,6.16698489,8
3,2013-10-24,206.2,207.3,171.9,203.7,188.1,184.22000625,133
4,2013-10-31,199.0,267.4,199.0,263.7,213.5,29.38886606,51
...,...,...,...,...,...,...,...,...
541,2024-02-15,51835.2,52991.8,50581.2,51866.9,51847.5,18432.30880237,187271
542,2024-02-22,51866.9,64015.8,50456.0,62487.8,56332.8,27037.88254313,276464
543,2024-02-29,62489.8,69218.0,59150.0,66098.9,64205.0,35782.24167977,397613
544,2024-03-07,66098.9,73666.5,65200.0,73082.4,70007.5,23257.17822467,322052
545,2024-03-14,73089.7,73734.0,69863.8,70061.2,71990.7,2941.75186935,37373

In [75]:
df.close

0        123.9
1        141.2
2        202.9
3        203.7
4        263.7
        ...
541    51866.9
542    62487.8
543    66098.9
544    73082.4
545    70061.2
Name: close, Length: 546, dtype: float64

In [82]:
df["MA100"] = calculate_moving_average(df.close.values, 100)
df.loc[df["datetime"] > datetime(2024, 2, 1)]

[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]

,datetime,open,high,low,close,vwap,volume,count,MA100
540,2024-02-08,44333.7,52136.8,44333.7,51835.1,48381.2,26475.56512968,224679,28308.732
541,2024-02-15,51835.2,52991.8,50581.2,51866.9,51847.5,18432.30880237,187271,28398.298
542,2024-02-22,51866.9,64015.8,50456.0,62487.8,56332.8,27037.88254313,276464,28552.583
543,2024-02-29,62489.8,69218.0,59150.0,66098.9,64205.0,35782.24167977,397613,28781.778
544,2024-03-07,66098.9,73666.5,65200.0,73082.4,70007.5,23257.17822467,322052,29101.102
545,2024-03-14,73089.7,73734.0,69863.8,70061.2,71990.7,2941.75186935,37373,29388.015

In [83]:
trading_view_data

,DateTime,open,high,low,close,Volume,MA100,MA50,EMA21,MA20,MA8
0,2011-12-19,3.19300,4.50000,3.18933,4.22500,548627.494657,2.761738,5.448742,4.749152,4.950492,3.016694
1,2011-12-26,4.22500,5.49990,3.81000,5.26766,485200.264821,2.814408,5.547636,4.796289,4.674090,3.305203
2,2012-01-02,5.26346,7.22000,4.65000,7.11358,831478.824369,2.885537,5.682171,5.006952,4.464207,3.819793
3,2012-01-09,7.08362,7.19100,5.81000,7.00177,762534.117275,2.955549,5.813359,5.188299,4.360789,4.420014
4,2012-01-16,7.00177,7.18888,4.64000,6.30970,854016.604782,3.018639,5.929955,5.290245,4.267375,4.898738
...,...,...,...,...,...,...,...,...,...,...,...
633,2024-02-05,42578.80000,48576.25000,42244.23000,48311.33000,124007.204529,28177.380400,31911.179800,38840.135645,38260.803500,43184.257500
634,2024-02-12,48317.79000,52829.25000,47694.17000,52127.48000,154129.198244,28285.881100,32505.149800,40048.076041,39467.408000,44321.570000
635,2024-02-19,52135.18000,52971.70000,50428.75000,51725.45000,103586.979290,28334.568900,33094.792000,41109.655492,40657.052500,45502.465000
636,2024-02-26,51731.94000,64005.20000,50907.81000,63148.92000,257332.623029,28501.898200,33796.731600,43113.224993,42455.770500,47903.292500
637,2024-03-04,63146.76000,70055.50000,59173.92000,69342.56000,304078.816055,28773.765000,34623.562800,45497.709993,44422.693000,51356.661250